Add wrapper script and entry points for osc, emacs and git.

diff --git a/label-install b/label-install
--- a/label-install
+++ b/label-install
@@ -1,18 +1,8 @@
 #!/bin/sh
-copy_to_usr_local_bin() {
+create_command_bin() {
 SCRIPT=$1
-if [ -d /host/usr/local/bin ]; then
-        TARGET=/host/usr/local/bin
-elif [ -d /host/bin ] ; then
-        TARGET=/host/bin
-else
-        echo "could not determine copy target"
-        exit 1
-fi
-
 if [ ! -e ${TARGET}/${SCRIPT} ]; then
-        echo "copy /container/${SCRIPT} in ${TARGET}/"
-        cp -av /container/${SCRIPT} ${TARGET}/
+        cd ${TARGET}; ln -s dev-env-wrapper.sh ${SCRIPT}
 else
         echo "${TARGET}/${SCRIPT} already exist, will not update it"
 fi
@@ -22,5 +12,27 @@ if [ ! -e ${TARGET}/${SCRIPT} ]; then
         echo "Failed to create ${TARGET}/${SCRIPT}"
         exit 1
 fi
-echo ${1}
-copy_to_usr_local_bin dev-env
+
+# Commands to create
+COMMANDS="emacs \
+osc \
+git \
+"
+
+# determime target directory
+# either /usrlocalbin or current user bin
+if [ -d /host/usr/local/bin ]; then
+        TARGET=/host/usr/local/bin
+elif [ -d /host/bin ] ; then
+        TARGET=/host/bin
+else
+        echo "could not determine copy target"
+        exit 1
+fi
+
+cp /container/dev-env-wrapper.sh ${TARGET}/dev-env-wrapper.sh
+cp /container/dev-env ${TARGET}/dev-env
+
+for COMMAND in ${COMMANDS}; do
+    create_command_bin ${COMMAND}
+done
